[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
dark-light = "1.0.0"
iced = "0.10.0"
iced_aw = "0.7.0"
